### ISSUE TITLE
Fixed window size

### ISSUE THREAD

**Issue by LORDTEK** [rzats/font-highlighting-editor#1]
https://postimg.org/image/z4zs467gv/

There is no "discard, save etc" because of fixed window size.

**Comment by rzats** [comment]
Whoops, I remember this issue 😄The code that determines the editor window's size is [this](https://github.com/rzats/font-highlighting-editor/blob/master/src/fonthighlightingeditor/tool/FontHighlightingFrame.java#L923-L931): it picks a specific size for each platform (manually tested on three VMs to prevent _this exact issue_), then makes the window fixed-size; looks like whatever size I've picked for Windows is not enough. In hindsight this was a terrible idea, but Swing isn't a great framework for adaptive interfaces so I had to make do.

I guess the appropriate solution for this is to just make the window resizable, with a reasonable maximum size (around 700x500). Will get to it in a few days 🙂

**Comment by rzats** [comment]
@LORDTEK: fixed this and pushed a new release. Let me know if the issue's resolved!

**Comment by LORDTEK** [comment]
I have checked it, window opened small size but it is not fixed size. Then I resized (bigger) the window. Yes it is now usable. However https://raw.githubusercontent.com/rzats/font-highlighting-editor/master/static/FontHighlightingEditor.zip this link did not work on my system. I wanted to see manual download but *.zip was not downloaded.

**Comment by rzats** [comment]
The correct link is https://github.com/rzats/font-highlighting-editor/releases/download/latest/FontHighlightingEditor.zip - I think GitHub has changed that in the last 6 months. (Also fixed the README, thanks again!)
